// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iticapital.proto

package iticapital

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Enumeration of portfolio statuses
type PortfolioStatus int32

const (
	PortfolioStatus_BROKER             PortfolioStatus = 0
	PortfolioStatus_TRUSTED_MANAGEMENT PortfolioStatus = 1
	PortfolioStatus_READ_ONLY          PortfolioStatus = 2
	PortfolioStatus_BLOCKED            PortfolioStatus = 3
	PortfolioStatus_RESTRICTED         PortfolioStatus = 4
	PortfolioStatus_AUTO_RESTRICTED    PortfolioStatus = 5
	PortfolioStatus_ORDER_NOT_SIGNED   PortfolioStatus = 6
)

var PortfolioStatus_name = map[int32]string{
	0: "BROKER",
	1: "TRUSTED_MANAGEMENT",
	2: "READ_ONLY",
	3: "BLOCKED",
	4: "RESTRICTED",
	5: "AUTO_RESTRICTED",
	6: "ORDER_NOT_SIGNED",
}

var PortfolioStatus_value = map[string]int32{
	"BROKER":             0,
	"TRUSTED_MANAGEMENT": 1,
	"READ_ONLY":          2,
	"BLOCKED":            3,
	"RESTRICTED":         4,
	"AUTO_RESTRICTED":    5,
	"ORDER_NOT_SIGNED":   6,
}

func (x PortfolioStatus) String() string {
	return proto.EnumName(PortfolioStatus_name, int32(x))
}

func (PortfolioStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{0}
}

type GetBarsRequest_Interval int32

const (
	GetBarsRequest_INVALID     GetBarsRequest_Interval = 0
	GetBarsRequest_MIN         GetBarsRequest_Interval = 1
	GetBarsRequest_FIVE_MIN    GetBarsRequest_Interval = 2
	GetBarsRequest_TEN_MIN     GetBarsRequest_Interval = 3
	GetBarsRequest_FIFTEEN_MIN GetBarsRequest_Interval = 4
	GetBarsRequest_THIRTY_MIN  GetBarsRequest_Interval = 5
	GetBarsRequest_HOUR        GetBarsRequest_Interval = 6
	GetBarsRequest_TWO_HOUR    GetBarsRequest_Interval = 7
	GetBarsRequest_FOUR_HOUR   GetBarsRequest_Interval = 8
	GetBarsRequest_DAY         GetBarsRequest_Interval = 9
	GetBarsRequest_WEEK        GetBarsRequest_Interval = 10
	GetBarsRequest_MONTH       GetBarsRequest_Interval = 11
	GetBarsRequest_QUARTER     GetBarsRequest_Interval = 12
	GetBarsRequest_YEAR        GetBarsRequest_Interval = 13
)

var GetBarsRequest_Interval_name = map[int32]string{
	0:  "INVALID",
	1:  "MIN",
	2:  "FIVE_MIN",
	3:  "TEN_MIN",
	4:  "FIFTEEN_MIN",
	5:  "THIRTY_MIN",
	6:  "HOUR",
	7:  "TWO_HOUR",
	8:  "FOUR_HOUR",
	9:  "DAY",
	10: "WEEK",
	11: "MONTH",
	12: "QUARTER",
	13: "YEAR",
}

var GetBarsRequest_Interval_value = map[string]int32{
	"INVALID":     0,
	"MIN":         1,
	"FIVE_MIN":    2,
	"TEN_MIN":     3,
	"FIFTEEN_MIN": 4,
	"THIRTY_MIN":  5,
	"HOUR":        6,
	"TWO_HOUR":    7,
	"FOUR_HOUR":   8,
	"DAY":         9,
	"WEEK":        10,
	"MONTH":       11,
	"QUARTER":     12,
	"YEAR":        13,
}

func (x GetBarsRequest_Interval) String() string {
	return proto.EnumName(GetBarsRequest_Interval_name, int32(x))
}

func (GetBarsRequest_Interval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{7, 0}
}

type GetMyPortfolioDataRequest_Mode int32

const (
	GetMyPortfolioDataRequest_INVALID GetMyPortfolioDataRequest_Mode = 0
	GetMyPortfolioDataRequest_ACTIVE  GetMyPortfolioDataRequest_Mode = 1
	GetMyPortfolioDataRequest_ALL     GetMyPortfolioDataRequest_Mode = 2
)

var GetMyPortfolioDataRequest_Mode_name = map[int32]string{
	0: "INVALID",
	1: "ACTIVE",
	2: "ALL",
}

var GetMyPortfolioDataRequest_Mode_value = map[string]int32{
	"INVALID": 0,
	"ACTIVE":  1,
	"ALL":     2,
}

func (x GetMyPortfolioDataRequest_Mode) String() string {
	return proto.EnumName(GetMyPortfolioDataRequest_Mode_name, int32(x))
}

func (GetMyPortfolioDataRequest_Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{10, 0}
}

type PlaceOrderRequest_Action int32

const (
	PlaceOrderRequest_INVALID_ACTION PlaceOrderRequest_Action = 0
	PlaceOrderRequest_BUY            PlaceOrderRequest_Action = 1
	PlaceOrderRequest_SELL           PlaceOrderRequest_Action = 2
	PlaceOrderRequest_SHORT          PlaceOrderRequest_Action = 3
	PlaceOrderRequest_COVER          PlaceOrderRequest_Action = 4
)

var PlaceOrderRequest_Action_name = map[int32]string{
	0: "INVALID_ACTION",
	1: "BUY",
	2: "SELL",
	3: "SHORT",
	4: "COVER",
}

var PlaceOrderRequest_Action_value = map[string]int32{
	"INVALID_ACTION": 0,
	"BUY":            1,
	"SELL":           2,
	"SHORT":          3,
	"COVER":          4,
}

func (x PlaceOrderRequest_Action) String() string {
	return proto.EnumName(PlaceOrderRequest_Action_name, int32(x))
}

func (PlaceOrderRequest_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{14, 0}
}

type PlaceOrderRequest_Type int32

const (
	PlaceOrderRequest_INVALID_TYPE PlaceOrderRequest_Type = 0
	PlaceOrderRequest_MARKET       PlaceOrderRequest_Type = 1
	PlaceOrderRequest_LIMIT        PlaceOrderRequest_Type = 2
	PlaceOrderRequest_STOP         PlaceOrderRequest_Type = 3
	PlaceOrderRequest_STOP_LIMIT   PlaceOrderRequest_Type = 4
)

var PlaceOrderRequest_Type_name = map[int32]string{
	0: "INVALID_TYPE",
	1: "MARKET",
	2: "LIMIT",
	3: "STOP",
	4: "STOP_LIMIT",
}

var PlaceOrderRequest_Type_value = map[string]int32{
	"INVALID_TYPE": 0,
	"MARKET":       1,
	"LIMIT":        2,
	"STOP":         3,
	"STOP_LIMIT":   4,
}

func (x PlaceOrderRequest_Type) String() string {
	return proto.EnumName(PlaceOrderRequest_Type_name, int32(x))
}

func (PlaceOrderRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{14, 1}
}

type PlaceOrderRequest_Validity int32

const (
	PlaceOrderRequest_INVALID_VALIDITY PlaceOrderRequest_Validity = 0
	PlaceOrderRequest_DAY              PlaceOrderRequest_Validity = 1
	PlaceOrderRequest_GTC              PlaceOrderRequest_Validity = 2
)

var PlaceOrderRequest_Validity_name = map[int32]string{
	0: "INVALID_VALIDITY",
	1: "DAY",
	2: "GTC",
}

var PlaceOrderRequest_Validity_value = map[string]int32{
	"INVALID_VALIDITY": 0,
	"DAY":              1,
	"GTC":              2,
}

func (x PlaceOrderRequest_Validity) String() string {
	return proto.EnumName(PlaceOrderRequest_Validity_name, int32(x))
}

func (PlaceOrderRequest_Validity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{14, 2}
}

// Empty stub: when method hasn't params or nothing to return
type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

// Default response with queue name, which contains events from method call
type Response struct {
	Queue                string   `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

// Response for method with two events queues: success and fails
type ResponseWithFailed struct {
	QueueSucceed         string   `protobuf:"bytes,1,opt,name=queueSucceed,proto3" json:"queueSucceed,omitempty"`
	QueueFailed          string   `protobuf:"bytes,2,opt,name=queueFailed,proto3" json:"queueFailed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseWithFailed) Reset()         { *m = ResponseWithFailed{} }
func (m *ResponseWithFailed) String() string { return proto.CompactTextString(m) }
func (*ResponseWithFailed) ProtoMessage()    {}
func (*ResponseWithFailed) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{2}
}

func (m *ResponseWithFailed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseWithFailed.Unmarshal(m, b)
}
func (m *ResponseWithFailed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseWithFailed.Marshal(b, m, deterministic)
}
func (m *ResponseWithFailed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseWithFailed.Merge(m, src)
}
func (m *ResponseWithFailed) XXX_Size() int {
	return xxx_messageInfo_ResponseWithFailed.Size(m)
}
func (m *ResponseWithFailed) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseWithFailed.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseWithFailed proto.InternalMessageInfo

func (m *ResponseWithFailed) GetQueueSucceed() string {
	if m != nil {
		return m.QueueSucceed
	}
	return ""
}

func (m *ResponseWithFailed) GetQueueFailed() string {
	if m != nil {
		return m.QueueFailed
	}
	return ""
}

// Response for ListenPortfolio method: contains queue names for all method events
type ListenPortfolioResponse struct {
	SetPortfolioQueue    string   `protobuf:"bytes,1,opt,name=setPortfolioQueue,proto3" json:"setPortfolioQueue,omitempty"`
	AddTradeQueue        string   `protobuf:"bytes,2,opt,name=addTradeQueue,proto3" json:"addTradeQueue,omitempty"`
	UpdateOrderQueue     string   `protobuf:"bytes,3,opt,name=updateOrderQueue,proto3" json:"updateOrderQueue,omitempty"`
	UpdatePositionQueue  string   `protobuf:"bytes,4,opt,name=updatePositionQueue,proto3" json:"updatePositionQueue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenPortfolioResponse) Reset()         { *m = ListenPortfolioResponse{} }
func (m *ListenPortfolioResponse) String() string { return proto.CompactTextString(m) }
func (*ListenPortfolioResponse) ProtoMessage()    {}
func (*ListenPortfolioResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{3}
}

func (m *ListenPortfolioResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenPortfolioResponse.Unmarshal(m, b)
}
func (m *ListenPortfolioResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenPortfolioResponse.Marshal(b, m, deterministic)
}
func (m *ListenPortfolioResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenPortfolioResponse.Merge(m, src)
}
func (m *ListenPortfolioResponse) XXX_Size() int {
	return xxx_messageInfo_ListenPortfolioResponse.Size(m)
}
func (m *ListenPortfolioResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenPortfolioResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListenPortfolioResponse proto.InternalMessageInfo

func (m *ListenPortfolioResponse) GetSetPortfolioQueue() string {
	if m != nil {
		return m.SetPortfolioQueue
	}
	return ""
}

func (m *ListenPortfolioResponse) GetAddTradeQueue() string {
	if m != nil {
		return m.AddTradeQueue
	}
	return ""
}

func (m *ListenPortfolioResponse) GetUpdateOrderQueue() string {
	if m != nil {
		return m.UpdateOrderQueue
	}
	return ""
}

func (m *ListenPortfolioResponse) GetUpdatePositionQueue() string {
	if m != nil {
		return m.UpdatePositionQueue
	}
	return ""
}

// Response for ListenPortfolio method: contains queue names for all method events
type GetMyPortfolioDataResponse struct {
	MyTradeQueue         string   `protobuf:"bytes,1,opt,name=myTradeQueue,proto3" json:"myTradeQueue,omitempty"`
	MyClosePosQueue      string   `protobuf:"bytes,2,opt,name=myClosePosQueue,proto3" json:"myClosePosQueue,omitempty"`
	MyOrderQueue         string   `protobuf:"bytes,3,opt,name=myOrderQueue,proto3" json:"myOrderQueue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMyPortfolioDataResponse) Reset()         { *m = GetMyPortfolioDataResponse{} }
func (m *GetMyPortfolioDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetMyPortfolioDataResponse) ProtoMessage()    {}
func (*GetMyPortfolioDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{4}
}

func (m *GetMyPortfolioDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyPortfolioDataResponse.Unmarshal(m, b)
}
func (m *GetMyPortfolioDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyPortfolioDataResponse.Marshal(b, m, deterministic)
}
func (m *GetMyPortfolioDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyPortfolioDataResponse.Merge(m, src)
}
func (m *GetMyPortfolioDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetMyPortfolioDataResponse.Size(m)
}
func (m *GetMyPortfolioDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyPortfolioDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyPortfolioDataResponse proto.InternalMessageInfo

func (m *GetMyPortfolioDataResponse) GetMyTradeQueue() string {
	if m != nil {
		return m.MyTradeQueue
	}
	return ""
}

func (m *GetMyPortfolioDataResponse) GetMyClosePosQueue() string {
	if m != nil {
		return m.MyClosePosQueue
	}
	return ""
}

func (m *GetMyPortfolioDataResponse) GetMyOrderQueue() string {
	if m != nil {
		return m.MyOrderQueue
	}
	return ""
}

// Symbol param for methods, which return operations over stock listings
type Symbol struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Symbol) Reset()         { *m = Symbol{} }
func (m *Symbol) String() string { return proto.CompactTextString(m) }
func (*Symbol) ProtoMessage()    {}
func (*Symbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{5}
}

func (m *Symbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Symbol.Unmarshal(m, b)
}
func (m *Symbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Symbol.Marshal(b, m, deterministic)
}
func (m *Symbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Symbol.Merge(m, src)
}
func (m *Symbol) XXX_Size() int {
	return xxx_messageInfo_Symbol.Size(m)
}
func (m *Symbol) XXX_DiscardUnknown() {
	xxx_messageInfo_Symbol.DiscardUnknown(m)
}

var xxx_messageInfo_Symbol proto.InternalMessageInfo

func (m *Symbol) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Portfolio param for method, which return operations over portfolio
type Portfolio struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portfolio) Reset()         { *m = Portfolio{} }
func (m *Portfolio) String() string { return proto.CompactTextString(m) }
func (*Portfolio) ProtoMessage()    {}
func (*Portfolio) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{6}
}

func (m *Portfolio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolio.Unmarshal(m, b)
}
func (m *Portfolio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolio.Marshal(b, m, deterministic)
}
func (m *Portfolio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolio.Merge(m, src)
}
func (m *Portfolio) XXX_Size() int {
	return xxx_messageInfo_Portfolio.Size(m)
}
func (m *Portfolio) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolio.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolio proto.InternalMessageInfo

func (m *Portfolio) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Request get bars
type GetBarsRequest struct {
	Symbol               *Symbol                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval             GetBarsRequest_Interval `protobuf:"varint,2,opt,name=interval,proto3,enum=iticapital.GetBarsRequest_Interval" json:"interval,omitempty"`
	Since                int64                   `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Count                int64                   `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetBarsRequest) Reset()         { *m = GetBarsRequest{} }
func (m *GetBarsRequest) String() string { return proto.CompactTextString(m) }
func (*GetBarsRequest) ProtoMessage()    {}
func (*GetBarsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{7}
}

func (m *GetBarsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBarsRequest.Unmarshal(m, b)
}
func (m *GetBarsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBarsRequest.Marshal(b, m, deterministic)
}
func (m *GetBarsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBarsRequest.Merge(m, src)
}
func (m *GetBarsRequest) XXX_Size() int {
	return xxx_messageInfo_GetBarsRequest.Size(m)
}
func (m *GetBarsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBarsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBarsRequest proto.InternalMessageInfo

func (m *GetBarsRequest) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *GetBarsRequest) GetInterval() GetBarsRequest_Interval {
	if m != nil {
		return m.Interval
	}
	return GetBarsRequest_INVALID
}

func (m *GetBarsRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetBarsRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type OrderCancelRequest struct {
	Portfolio            *Portfolio `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Symbol               *Symbol    `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId              string     `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderCancelRequest) Reset()         { *m = OrderCancelRequest{} }
func (m *OrderCancelRequest) String() string { return proto.CompactTextString(m) }
func (*OrderCancelRequest) ProtoMessage()    {}
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{8}
}

func (m *OrderCancelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancelRequest.Unmarshal(m, b)
}
func (m *OrderCancelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancelRequest.Marshal(b, m, deterministic)
}
func (m *OrderCancelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancelRequest.Merge(m, src)
}
func (m *OrderCancelRequest) XXX_Size() int {
	return xxx_messageInfo_OrderCancelRequest.Size(m)
}
func (m *OrderCancelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancelRequest proto.InternalMessageInfo

func (m *OrderCancelRequest) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

func (m *OrderCancelRequest) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *OrderCancelRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type ConnectRequest struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 uint64   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Login                string   `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{9}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ConnectRequest) GetPort() uint64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConnectRequest) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *ConnectRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetMyPortfolioDataRequest struct {
	Mode                 GetMyPortfolioDataRequest_Mode `protobuf:"varint,1,opt,name=mode,proto3,enum=iticapital.GetMyPortfolioDataRequest_Mode" json:"mode,omitempty"`
	Portfolio            *Portfolio                     `protobuf:"bytes,2,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *GetMyPortfolioDataRequest) Reset()         { *m = GetMyPortfolioDataRequest{} }
func (m *GetMyPortfolioDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetMyPortfolioDataRequest) ProtoMessage()    {}
func (*GetMyPortfolioDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{10}
}

func (m *GetMyPortfolioDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMyPortfolioDataRequest.Unmarshal(m, b)
}
func (m *GetMyPortfolioDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMyPortfolioDataRequest.Marshal(b, m, deterministic)
}
func (m *GetMyPortfolioDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMyPortfolioDataRequest.Merge(m, src)
}
func (m *GetMyPortfolioDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetMyPortfolioDataRequest.Size(m)
}
func (m *GetMyPortfolioDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMyPortfolioDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMyPortfolioDataRequest proto.InternalMessageInfo

func (m *GetMyPortfolioDataRequest) GetMode() GetMyPortfolioDataRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return GetMyPortfolioDataRequest_INVALID
}

func (m *GetMyPortfolioDataRequest) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

type GetTradesRequest struct {
	Symbol               *Symbol  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	From                 int64    `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTradesRequest) Reset()         { *m = GetTradesRequest{} }
func (m *GetTradesRequest) String() string { return proto.CompactTextString(m) }
func (*GetTradesRequest) ProtoMessage()    {}
func (*GetTradesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{11}
}

func (m *GetTradesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTradesRequest.Unmarshal(m, b)
}
func (m *GetTradesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTradesRequest.Marshal(b, m, deterministic)
}
func (m *GetTradesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTradesRequest.Merge(m, src)
}
func (m *GetTradesRequest) XXX_Size() int {
	return xxx_messageInfo_GetTradesRequest.Size(m)
}
func (m *GetTradesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTradesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTradesRequest proto.InternalMessageInfo

func (m *GetTradesRequest) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *GetTradesRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *GetTradesRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type IsConnectedResponse struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsConnectedResponse) Reset()         { *m = IsConnectedResponse{} }
func (m *IsConnectedResponse) String() string { return proto.CompactTextString(m) }
func (*IsConnectedResponse) ProtoMessage()    {}
func (*IsConnectedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{12}
}

func (m *IsConnectedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsConnectedResponse.Unmarshal(m, b)
}
func (m *IsConnectedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsConnectedResponse.Marshal(b, m, deterministic)
}
func (m *IsConnectedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsConnectedResponse.Merge(m, src)
}
func (m *IsConnectedResponse) XXX_Size() int {
	return xxx_messageInfo_IsConnectedResponse.Size(m)
}
func (m *IsConnectedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsConnectedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsConnectedResponse proto.InternalMessageInfo

func (m *IsConnectedResponse) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type MoveOrderRequest struct {
	Portfolio            *Portfolio `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Symbol               *Symbol    `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId              string     `protobuf:"bytes,3,opt,name=orderId,proto3" json:"orderId,omitempty"`
	TargetPrice          float64    `protobuf:"fixed64,4,opt,name=targetPrice,proto3" json:"targetPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MoveOrderRequest) Reset()         { *m = MoveOrderRequest{} }
func (m *MoveOrderRequest) String() string { return proto.CompactTextString(m) }
func (*MoveOrderRequest) ProtoMessage()    {}
func (*MoveOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{13}
}

func (m *MoveOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveOrderRequest.Unmarshal(m, b)
}
func (m *MoveOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveOrderRequest.Marshal(b, m, deterministic)
}
func (m *MoveOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveOrderRequest.Merge(m, src)
}
func (m *MoveOrderRequest) XXX_Size() int {
	return xxx_messageInfo_MoveOrderRequest.Size(m)
}
func (m *MoveOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveOrderRequest proto.InternalMessageInfo

func (m *MoveOrderRequest) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

func (m *MoveOrderRequest) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *MoveOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *MoveOrderRequest) GetTargetPrice() float64 {
	if m != nil {
		return m.TargetPrice
	}
	return 0
}

type PlaceOrderRequest struct {
	Portfolio            *Portfolio                 `protobuf:"bytes,1,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
	Symbol               *Symbol                    `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Action               PlaceOrderRequest_Action   `protobuf:"varint,3,opt,name=action,proto3,enum=iticapital.PlaceOrderRequest_Action" json:"action,omitempty"`
	Type                 PlaceOrderRequest_Type     `protobuf:"varint,4,opt,name=type,proto3,enum=iticapital.PlaceOrderRequest_Type" json:"type,omitempty"`
	Validity             PlaceOrderRequest_Validity `protobuf:"varint,5,opt,name=validity,proto3,enum=iticapital.PlaceOrderRequest_Validity" json:"validity,omitempty"`
	Price                float64                    `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Amount               float64                    `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	PriceStop            float64                    `protobuf:"fixed64,8,opt,name=priceStop,proto3" json:"priceStop,omitempty"`
	UniqueId             int64                      `protobuf:"varint,9,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PlaceOrderRequest) Reset()         { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()    {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed3f1da7a6fc4153, []int{14}
}

func (m *PlaceOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceOrderRequest.Unmarshal(m, b)
}
func (m *PlaceOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceOrderRequest.Marshal(b, m, deterministic)
}
func (m *PlaceOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceOrderRequest.Merge(m, src)
}
func (m *PlaceOrderRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceOrderRequest.Size(m)
}
func (m *PlaceOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceOrderRequest proto.InternalMessageInfo

func (m *PlaceOrderRequest) GetPortfolio() *Portfolio {
	if m != nil {
		return m.Portfolio
	}
	return nil
}

func (m *PlaceOrderRequest) GetSymbol() *Symbol {
	if m != nil {
		return m.Symbol
	}
	return nil
}

func (m *PlaceOrderRequest) GetAction() PlaceOrderRequest_Action {
	if m != nil {
		return m.Action
	}
	return PlaceOrderRequest_INVALID_ACTION
}

func (m *PlaceOrderRequest) GetType() PlaceOrderRequest_Type {
	if m != nil {
		return m.Type
	}
	return PlaceOrderRequest_INVALID_TYPE
}

func (m *PlaceOrderRequest) GetValidity() PlaceOrderRequest_Validity {
	if m != nil {
		return m.Validity
	}
	return PlaceOrderRequest_INVALID_VALIDITY
}

func (m *PlaceOrderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PlaceOrderRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PlaceOrderRequest) GetPriceStop() float64 {
	if m != nil {
		return m.PriceStop
	}
	return 0
}

func (m *PlaceOrderRequest) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

func init() {
	proto.RegisterEnum("iticapital.PortfolioStatus", PortfolioStatus_name, PortfolioStatus_value)
	proto.RegisterEnum("iticapital.GetBarsRequest_Interval", GetBarsRequest_Interval_name, GetBarsRequest_Interval_value)
	proto.RegisterEnum("iticapital.GetMyPortfolioDataRequest_Mode", GetMyPortfolioDataRequest_Mode_name, GetMyPortfolioDataRequest_Mode_value)
	proto.RegisterEnum("iticapital.PlaceOrderRequest_Action", PlaceOrderRequest_Action_name, PlaceOrderRequest_Action_value)
	proto.RegisterEnum("iticapital.PlaceOrderRequest_Type", PlaceOrderRequest_Type_name, PlaceOrderRequest_Type_value)
	proto.RegisterEnum("iticapital.PlaceOrderRequest_Validity", PlaceOrderRequest_Validity_name, PlaceOrderRequest_Validity_value)
	proto.RegisterType((*Nothing)(nil), "iticapital.Nothing")
	proto.RegisterType((*Response)(nil), "iticapital.Response")
	proto.RegisterType((*ResponseWithFailed)(nil), "iticapital.ResponseWithFailed")
	proto.RegisterType((*ListenPortfolioResponse)(nil), "iticapital.ListenPortfolioResponse")
	proto.RegisterType((*GetMyPortfolioDataResponse)(nil), "iticapital.GetMyPortfolioDataResponse")
	proto.RegisterType((*Symbol)(nil), "iticapital.Symbol")
	proto.RegisterType((*Portfolio)(nil), "iticapital.Portfolio")
	proto.RegisterType((*GetBarsRequest)(nil), "iticapital.GetBarsRequest")
	proto.RegisterType((*OrderCancelRequest)(nil), "iticapital.OrderCancelRequest")
	proto.RegisterType((*ConnectRequest)(nil), "iticapital.ConnectRequest")
	proto.RegisterType((*GetMyPortfolioDataRequest)(nil), "iticapital.GetMyPortfolioDataRequest")
	proto.RegisterType((*GetTradesRequest)(nil), "iticapital.GetTradesRequest")
	proto.RegisterType((*IsConnectedResponse)(nil), "iticapital.IsConnectedResponse")
	proto.RegisterType((*MoveOrderRequest)(nil), "iticapital.MoveOrderRequest")
	proto.RegisterType((*PlaceOrderRequest)(nil), "iticapital.PlaceOrderRequest")
}

func init() {
	proto.RegisterFile("iticapital.proto", fileDescriptor_ed3f1da7a6fc4153)
}

var fileDescriptor_ed3f1da7a6fc4153 = []byte{
	// 1327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xdd, 0x6e, 0x1a, 0x47,
	0x14, 0xf6, 0xc2, 0x1a, 0xb3, 0x07, 0x8c, 0x27, 0xe3, 0x34, 0x75, 0x51, 0x9a, 0xa6, 0xdb, 0x34,
	0x8a, 0xdc, 0xca, 0xaa, 0x88, 0x54, 0x35, 0xfd, 0x8b, 0xd6, 0xb0, 0xc6, 0x2b, 0x03, 0x4b, 0x86,
	0xb1, 0x23, 0x7a, 0x83, 0x36, 0xec, 0x24, 0x59, 0x05, 0xb3, 0x84, 0x1d, 0x5c, 0xf1, 0x0e, 0x55,
	0xfb, 0x28, 0xbd, 0xad, 0xfa, 0x0a, 0x7d, 0x85, 0xf6, 0xae, 0x0f, 0x52, 0xcd, 0xcc, 0xb2, 0xec,
	0xda, 0xe0, 0x24, 0xbd, 0x68, 0x6f, 0x10, 0xe7, 0xcc, 0x77, 0x7e, 0xe6, 0xfc, 0xce, 0x02, 0x0a,
	0x78, 0x30, 0xf4, 0x26, 0x01, 0xf7, 0x46, 0x07, 0x93, 0x69, 0xc8, 0x43, 0x0c, 0x4b, 0x8e, 0x69,
	0xc0, 0x56, 0x27, 0xe4, 0x2f, 0x83, 0xf1, 0x0b, 0xf3, 0x2e, 0x14, 0x09, 0x8b, 0x26, 0xe1, 0x38,
	0x62, 0xf8, 0x26, 0x6c, 0xbe, 0x9e, 0xb1, 0x19, 0xdb, 0xd3, 0xee, 0x6a, 0x0f, 0x0c, 0xa2, 0x08,
	0xf3, 0x07, 0xc0, 0x0b, 0xc4, 0xd3, 0x80, 0xbf, 0x3c, 0xf2, 0x82, 0x11, 0xf3, 0xb1, 0x09, 0x65,
	0x79, 0xdc, 0x9b, 0x0d, 0x87, 0x8c, 0xf9, 0xb1, 0x48, 0x86, 0x87, 0xef, 0x42, 0x49, 0xd2, 0x4a,
	0x64, 0x2f, 0x27, 0x21, 0x69, 0x96, 0xf9, 0x87, 0x06, 0xef, 0xb7, 0x82, 0x88, 0xb3, 0x71, 0x37,
	0x9c, 0xf2, 0xe7, 0xe1, 0x28, 0x08, 0x13, 0x6f, 0x3e, 0x87, 0x1b, 0x11, 0xe3, 0x09, 0xff, 0x49,
	0xca, 0xb3, 0xab, 0x07, 0xf8, 0x1e, 0x6c, 0x7b, 0xbe, 0x4f, 0xa7, 0x9e, 0xcf, 0x14, 0x52, 0x59,
	0xcb, 0x32, 0xf1, 0x3e, 0xa0, 0xd9, 0xc4, 0xf7, 0x38, 0x73, 0xa7, 0x3e, 0x9b, 0x2a, 0x60, 0x5e,
	0x02, 0xaf, 0xf0, 0xf1, 0x17, 0xb0, 0xab, 0x78, 0xdd, 0x30, 0x0a, 0x78, 0x10, 0x8e, 0x15, 0x5c,
	0x97, 0xf0, 0x55, 0x47, 0xe6, 0xcf, 0x1a, 0x54, 0x9b, 0x8c, 0xb7, 0xe7, 0x89, 0x6f, 0x0d, 0x8f,
	0x7b, 0xc9, 0x85, 0x4c, 0x28, 0x9f, 0xcf, 0x53, 0x1e, 0xc6, 0x21, 0x4b, 0xf3, 0xf0, 0x03, 0xd8,
	0x39, 0x9f, 0xd7, 0x47, 0x61, 0x24, 0x54, 0xa7, 0x2f, 0x72, 0x99, 0xad, 0xb4, 0x5d, 0xb9, 0x46,
	0x86, 0x67, 0xde, 0x81, 0x42, 0x6f, 0x7e, 0xfe, 0x2c, 0x1c, 0x89, 0xd4, 0x5e, 0x78, 0xa3, 0x65,
	0x6a, 0x25, 0x61, 0x7e, 0x0c, 0x46, 0xe2, 0xea, 0x1a, 0xc8, 0xdf, 0x39, 0xa8, 0x34, 0x19, 0x3f,
	0xf4, 0xa6, 0x11, 0x61, 0xaf, 0x67, 0x2c, 0xe2, 0x78, 0x1f, 0x0a, 0x91, 0xd4, 0x2a, 0x91, 0xa5,
	0x1a, 0x3e, 0x48, 0x15, 0x9b, 0xb2, 0x47, 0x62, 0x04, 0x7e, 0x0c, 0xc5, 0x60, 0xcc, 0xd9, 0xf4,
	0xc2, 0x1b, 0xc9, 0x8b, 0x54, 0x6a, 0x9f, 0xa4, 0xd1, 0x59, 0xcd, 0x07, 0x4e, 0x0c, 0x25, 0x89,
	0x90, 0xf0, 0x2a, 0x0a, 0xc6, 0x43, 0x75, 0xbf, 0x3c, 0x51, 0x84, 0xe0, 0x0e, 0xc3, 0xd9, 0x98,
	0xcb, 0x6c, 0xe4, 0x89, 0x22, 0xcc, 0xdf, 0x34, 0x28, 0x2e, 0x54, 0xe0, 0x12, 0x6c, 0x39, 0x9d,
	0x33, 0xab, 0xe5, 0x34, 0xd0, 0x06, 0xde, 0x82, 0x7c, 0xdb, 0xe9, 0x20, 0x0d, 0x97, 0xa1, 0x78,
	0xe4, 0x9c, 0xd9, 0x03, 0x41, 0xe5, 0x04, 0x86, 0xda, 0x1d, 0x49, 0xe4, 0xf1, 0x0e, 0x94, 0x8e,
	0x9c, 0x23, 0x6a, 0xc7, 0x0c, 0x1d, 0x57, 0x00, 0xe8, 0xb1, 0x43, 0x68, 0x5f, 0xd2, 0x9b, 0xb8,
	0x08, 0xfa, 0xb1, 0x7b, 0x4a, 0x50, 0x41, 0x68, 0xa1, 0x4f, 0xdd, 0x81, 0xa4, 0xb6, 0xf0, 0x36,
	0x18, 0x47, 0xee, 0x29, 0x51, 0x64, 0x51, 0xd8, 0x6a, 0x58, 0x7d, 0x64, 0x08, 0xfc, 0x53, 0xdb,
	0x3e, 0x41, 0x80, 0x0d, 0xd8, 0x6c, 0xbb, 0x1d, 0x7a, 0x8c, 0x4a, 0xc2, 0xe4, 0x93, 0x53, 0x8b,
	0x50, 0x9b, 0xa0, 0xb2, 0x40, 0xf4, 0x6d, 0x8b, 0xa0, 0x6d, 0xf3, 0x17, 0x0d, 0xb0, 0x4c, 0x5c,
	0xdd, 0x1b, 0x0f, 0xd9, 0x68, 0x11, 0xea, 0x87, 0x60, 0x4c, 0x16, 0x09, 0x8a, 0xa3, 0xfd, 0x5e,
	0x3a, 0x7e, 0xcb, 0xae, 0x59, 0xe2, 0x52, 0xf9, 0xc9, 0xbd, 0x31, 0x3f, 0x7b, 0xb0, 0x15, 0x0a,
	0xb3, 0x8e, 0x1f, 0x17, 0xd0, 0x82, 0x34, 0x9f, 0x43, 0xa5, 0x1e, 0x8e, 0xc7, 0x6c, 0xc8, 0x17,
	0xce, 0x54, 0x20, 0x17, 0x4c, 0xe2, 0xea, 0xc8, 0x05, 0x13, 0x8c, 0x41, 0x17, 0x46, 0xa5, 0x15,
	0x9d, 0xc8, 0xff, 0x22, 0x31, 0xa3, 0xf0, 0x45, 0x30, 0x8e, 0xb5, 0x29, 0x02, 0x57, 0xa1, 0x38,
	0xf1, 0xa2, 0xe8, 0xc7, 0x70, 0xea, 0xc7, 0xfd, 0x93, 0xd0, 0xe6, 0xef, 0x1a, 0x7c, 0xb0, 0xaa,
	0x69, 0x94, 0xcd, 0xef, 0x41, 0x3f, 0x0f, 0x7d, 0x55, 0x93, 0x95, 0xda, 0xfe, 0xa5, 0xda, 0x59,
	0x2d, 0x74, 0xd0, 0x0e, 0x7d, 0x46, 0xa4, 0x5c, 0x36, 0x80, 0xb9, 0xb7, 0x0b, 0xa0, 0xf9, 0x00,
	0x74, 0xa1, 0x22, 0x5b, 0x42, 0x00, 0x05, 0xab, 0x4e, 0x9d, 0x33, 0x1b, 0x69, 0x22, 0xc5, 0x56,
	0xab, 0x85, 0x72, 0xe6, 0x4b, 0x40, 0x4d, 0xc6, 0x65, 0xff, 0xfe, 0xab, 0xf6, 0xc0, 0xa0, 0x3f,
	0x9f, 0x86, 0xe7, 0xd2, 0xb3, 0x3c, 0x91, 0xff, 0x97, 0xb5, 0x9d, 0x4f, 0xd7, 0xf6, 0x67, 0xb0,
	0xeb, 0x44, 0x71, 0x42, 0x98, 0x9f, 0x1e, 0xd9, 0xcb, 0xa6, 0x2d, 0x2e, 0x9a, 0xf6, 0x57, 0x0d,
	0x50, 0x3b, 0xbc, 0x50, 0xd3, 0xec, 0xff, 0xaf, 0x25, 0xb1, 0x08, 0xb8, 0x37, 0x7d, 0xc1, 0x78,
	0x77, 0x1a, 0x0c, 0xd5, 0x08, 0xd5, 0x48, 0x9a, 0x65, 0xfe, 0xa9, 0xc3, 0x8d, 0xee, 0xc8, 0x1b,
	0xfe, 0xc7, 0x2e, 0x7f, 0x0b, 0x05, 0x6f, 0x28, 0x06, 0xb8, 0xf4, 0xb8, 0x52, 0xbb, 0x97, 0xd1,
	0x7e, 0xd9, 0x9f, 0x03, 0x4b, 0x62, 0x49, 0x2c, 0x83, 0xbf, 0x04, 0x9d, 0xcf, 0x27, 0xea, 0x3e,
	0x95, 0x9a, 0x79, 0xbd, 0x2c, 0x9d, 0x4f, 0x18, 0x91, 0x78, 0x7c, 0x08, 0xc5, 0x0b, 0x6f, 0x14,
	0xf8, 0x01, 0x9f, 0xef, 0x6d, 0x4a, 0xd9, 0xfb, 0xd7, 0xcb, 0x9e, 0xc5, 0x68, 0x92, 0xc8, 0x89,
	0xc4, 0x4f, 0x64, 0x30, 0x0b, 0x32, 0x98, 0x8a, 0xc0, 0xb7, 0xa0, 0xe0, 0x9d, 0xcb, 0xe2, 0xd9,
	0x92, 0xec, 0x98, 0xc2, 0xb7, 0xc1, 0x90, 0x80, 0x1e, 0x0f, 0x27, 0x7b, 0x45, 0x79, 0xb4, 0x64,
	0x88, 0xf6, 0x9c, 0x8d, 0x83, 0xd7, 0x33, 0xe6, 0xf8, 0x7b, 0x86, 0x2c, 0xba, 0x84, 0x36, 0x6d,
	0x28, 0xa8, 0x5b, 0x63, 0x0c, 0x95, 0xb8, 0x1b, 0x06, 0xa2, 0x11, 0xdc, 0x8e, 0x9a, 0xab, 0x87,
	0xa7, 0x7d, 0xa4, 0x89, 0x49, 0xd6, 0xb3, 0x45, 0x4b, 0x88, 0x59, 0xd7, 0x3b, 0x76, 0x09, 0x45,
	0x79, 0xf1, 0xb7, 0xee, 0x9e, 0xd9, 0x04, 0xe9, 0xa6, 0x03, 0xba, 0x08, 0x00, 0x46, 0x50, 0x5e,
	0x28, 0xa1, 0xfd, 0xae, 0xad, 0xfa, 0xaa, 0x6d, 0x91, 0x13, 0x9b, 0x22, 0x4d, 0x08, 0xb4, 0x9c,
	0xb6, 0x43, 0x51, 0x4e, 0x2a, 0xa4, 0x6e, 0x17, 0xe5, 0xc5, 0x18, 0x16, 0xff, 0x06, 0xea, 0x44,
	0x37, 0x6b, 0x50, 0x3c, 0x5b, 0x46, 0x01, 0x2d, 0xd4, 0xc9, 0x5f, 0x87, 0xf6, 0x95, 0x57, 0x62,
	0x02, 0xcb, 0x3e, 0x6d, 0xd2, 0x3a, 0xca, 0xed, 0xff, 0xa4, 0xc1, 0x4e, 0x52, 0x2c, 0x3d, 0xee,
	0xf1, 0x59, 0x24, 0x0c, 0x1f, 0x12, 0xf7, 0xc4, 0x26, 0x68, 0x03, 0xdf, 0x02, 0x4c, 0xc9, 0x69,
	0x8f, 0xda, 0x8d, 0x41, 0xdb, 0xea, 0x58, 0x4d, 0xbb, 0x6d, 0x77, 0x84, 0x43, 0xdb, 0x60, 0x10,
	0xdb, 0x6a, 0x0c, 0xdc, 0x4e, 0xab, 0xaf, 0xf6, 0xc5, 0x61, 0xcb, 0xad, 0x9f, 0xd8, 0x0d, 0xe5,
	0x17, 0xb1, 0x7b, 0x94, 0x38, 0x75, 0x6a, 0x37, 0x90, 0x8e, 0x77, 0x61, 0xc7, 0x3a, 0xa5, 0xee,
	0x20, 0xc5, 0xdc, 0x14, 0x0e, 0xba, 0xa4, 0x61, 0x93, 0x41, 0xc7, 0xa5, 0x83, 0x9e, 0xd3, 0xec,
	0xd8, 0x0d, 0x54, 0xa8, 0xfd, 0x65, 0xc0, 0xb6, 0x43, 0x9d, 0xba, 0x4a, 0xb8, 0xd5, 0x75, 0xf0,
	0x23, 0x28, 0xab, 0xc9, 0x7f, 0x18, 0xf8, 0x56, 0xf4, 0x0a, 0xaf, 0x28, 0xda, 0xea, 0x6e, 0x9a,
	0xb7, 0x78, 0xbf, 0x6d, 0x60, 0x17, 0x4a, 0x4a, 0x54, 0x96, 0x0c, 0xbe, 0x93, 0x46, 0x5d, 0x5d,
	0x29, 0xd5, 0xcc, 0xf9, 0xd5, 0x87, 0x9d, 0xb9, 0x81, 0x1f, 0xc3, 0x8e, 0x12, 0x59, 0xbe, 0x0d,
	0x56, 0x77, 0xdd, 0x3a, 0x8f, 0x92, 0xcb, 0x3c, 0x99, 0x85, 0x9c, 0x45, 0xef, 0x72, 0x99, 0xaf,
	0x16, 0x97, 0xa1, 0xc1, 0xf0, 0xd5, 0x3b, 0x49, 0x7e, 0x07, 0x5b, 0xf1, 0x78, 0xc4, 0xd5, 0x34,
	0x22, 0xbb, 0xc4, 0xaa, 0x37, 0x57, 0x5d, 0x5f, 0x89, 0xc7, 0x8f, 0x91, 0xac, 0x78, 0xf6, 0x85,
	0xb2, 0x56, 0x9c, 0x01, 0xbe, 0xba, 0x8f, 0xf0, 0xa7, 0x6f, 0xb5, 0xaf, 0xaa, 0xf7, 0xdf, 0x04,
	0x4b, 0xcc, 0x3c, 0x96, 0xfb, 0x26, 0x39, 0x15, 0x4f, 0x67, 0xbc, 0x2a, 0x1e, 0x6b, 0xfd, 0xb4,
	0xc0, 0x48, 0x16, 0x16, 0xbe, 0x7d, 0xc9, 0x6e, 0x66, 0x8f, 0xad, 0x55, 0xf1, 0x08, 0xa0, 0xc9,
	0xb8, 0x4a, 0x46, 0xf4, 0x6e, 0xd6, 0x6d, 0x28, 0xa5, 0x96, 0xd8, 0x6a, 0xd9, 0x8f, 0xd2, 0xcc,
	0x15, 0x2b, 0xcf, 0xdc, 0xc0, 0xdf, 0xc0, 0xb6, 0xfa, 0x68, 0x50, 0xcd, 0xb2, 0xba, 0x4c, 0xd6,
	0xf9, 0xe0, 0xc2, 0xce, 0xa5, 0x2f, 0x8e, 0x75, 0xd5, 0x9d, 0x79, 0xa9, 0xae, 0xf9, 0x4a, 0x31,
	0x37, 0xf0, 0xd7, 0x50, 0x56, 0x87, 0xd7, 0x54, 0xfb, 0xfa, 0x58, 0x96, 0x94, 0xec, 0xfa, 0x72,
	0x5f, 0x27, 0x7a, 0x02, 0x46, 0xb2, 0xe2, 0xb3, 0x99, 0xbc, 0xbc, 0xf9, 0xdf, 0xa2, 0xe5, 0xdb,
	0x00, 0xcb, 0xad, 0x83, 0x3f, 0xbc, 0x76, 0x1b, 0xbd, 0x59, 0xdd, 0xb3, 0x82, 0xfc, 0xe4, 0x7c,
	0xf8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0xa7, 0x3b, 0xd3, 0x86, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ITICapitalAPIClient is the client API for ITICapitalAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ITICapitalAPIClient interface {
	CancelBidAsk(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error)
	CancelOrder(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error)
	CancelPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Nothing, error)
	CancelQuotes(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error)
	CancelTicks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error)
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Response, error)
	GetBars(ctx context.Context, in *GetBarsRequest, opts ...grpc.CallOption) (*Response, error)
	GetMyPortfolioData(ctx context.Context, in *GetMyPortfolioDataRequest, opts ...grpc.CallOption) (*GetMyPortfolioDataResponse, error)
	GetPortfolioList(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Response, error)
	GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*Response, error)
	GetSymbols(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Response, error)
	IsConnected(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*IsConnectedResponse, error)
	ListenBidAsks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error)
	ListenPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*ListenPortfolioResponse, error)
	ListenQuotes(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error)
	ListenTicks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error)
	MoveOrder(ctx context.Context, in *MoveOrderRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error)
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error)
}

type iTICapitalAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewITICapitalAPIClient(cc grpc.ClientConnInterface) ITICapitalAPIClient {
	return &iTICapitalAPIClient{cc}
}

func (c *iTICapitalAPIClient) CancelBidAsk(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/CancelBidAsk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) CancelOrder(ctx context.Context, in *OrderCancelRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error) {
	out := new(ResponseWithFailed)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) CancelPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/CancelPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) CancelQuotes(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/CancelQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) CancelTicks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/CancelTicks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) GetBars(ctx context.Context, in *GetBarsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/GetBars", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) GetMyPortfolioData(ctx context.Context, in *GetMyPortfolioDataRequest, opts ...grpc.CallOption) (*GetMyPortfolioDataResponse, error) {
	out := new(GetMyPortfolioDataResponse)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/GetMyPortfolioData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) GetPortfolioList(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/GetPortfolioList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) GetTrades(ctx context.Context, in *GetTradesRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/GetTrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) GetSymbols(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/GetSymbols", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) IsConnected(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*IsConnectedResponse, error) {
	out := new(IsConnectedResponse)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/IsConnected", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) ListenBidAsks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/ListenBidAsks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) ListenPortfolio(ctx context.Context, in *Portfolio, opts ...grpc.CallOption) (*ListenPortfolioResponse, error) {
	out := new(ListenPortfolioResponse)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/ListenPortfolio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) ListenQuotes(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/ListenQuotes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) ListenTicks(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/ListenTicks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) MoveOrder(ctx context.Context, in *MoveOrderRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error) {
	out := new(ResponseWithFailed)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/MoveOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iTICapitalAPIClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*ResponseWithFailed, error) {
	out := new(ResponseWithFailed)
	err := c.cc.Invoke(ctx, "/iticapital.ITICapitalAPI/PlaceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ITICapitalAPIServer is the server API for ITICapitalAPI service.
type ITICapitalAPIServer interface {
	CancelBidAsk(context.Context, *Symbol) (*Nothing, error)
	CancelOrder(context.Context, *OrderCancelRequest) (*ResponseWithFailed, error)
	CancelPortfolio(context.Context, *Portfolio) (*Nothing, error)
	CancelQuotes(context.Context, *Symbol) (*Nothing, error)
	CancelTicks(context.Context, *Symbol) (*Nothing, error)
	Connect(context.Context, *ConnectRequest) (*Response, error)
	GetBars(context.Context, *GetBarsRequest) (*Response, error)
	GetMyPortfolioData(context.Context, *GetMyPortfolioDataRequest) (*GetMyPortfolioDataResponse, error)
	GetPortfolioList(context.Context, *Nothing) (*Response, error)
	GetTrades(context.Context, *GetTradesRequest) (*Response, error)
	GetSymbols(context.Context, *Nothing) (*Response, error)
	IsConnected(context.Context, *Nothing) (*IsConnectedResponse, error)
	ListenBidAsks(context.Context, *Symbol) (*Response, error)
	ListenPortfolio(context.Context, *Portfolio) (*ListenPortfolioResponse, error)
	ListenQuotes(context.Context, *Symbol) (*Response, error)
	ListenTicks(context.Context, *Symbol) (*Response, error)
	MoveOrder(context.Context, *MoveOrderRequest) (*ResponseWithFailed, error)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*ResponseWithFailed, error)
}

// UnimplementedITICapitalAPIServer can be embedded to have forward compatible implementations.
type UnimplementedITICapitalAPIServer struct {
}

func (*UnimplementedITICapitalAPIServer) CancelBidAsk(ctx context.Context, req *Symbol) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBidAsk not implemented")
}
func (*UnimplementedITICapitalAPIServer) CancelOrder(ctx context.Context, req *OrderCancelRequest) (*ResponseWithFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedITICapitalAPIServer) CancelPortfolio(ctx context.Context, req *Portfolio) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelPortfolio not implemented")
}
func (*UnimplementedITICapitalAPIServer) CancelQuotes(ctx context.Context, req *Symbol) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQuotes not implemented")
}
func (*UnimplementedITICapitalAPIServer) CancelTicks(ctx context.Context, req *Symbol) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTicks not implemented")
}
func (*UnimplementedITICapitalAPIServer) Connect(ctx context.Context, req *ConnectRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedITICapitalAPIServer) GetBars(ctx context.Context, req *GetBarsRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBars not implemented")
}
func (*UnimplementedITICapitalAPIServer) GetMyPortfolioData(ctx context.Context, req *GetMyPortfolioDataRequest) (*GetMyPortfolioDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyPortfolioData not implemented")
}
func (*UnimplementedITICapitalAPIServer) GetPortfolioList(ctx context.Context, req *Nothing) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortfolioList not implemented")
}
func (*UnimplementedITICapitalAPIServer) GetTrades(ctx context.Context, req *GetTradesRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrades not implemented")
}
func (*UnimplementedITICapitalAPIServer) GetSymbols(ctx context.Context, req *Nothing) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (*UnimplementedITICapitalAPIServer) IsConnected(ctx context.Context, req *Nothing) (*IsConnectedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsConnected not implemented")
}
func (*UnimplementedITICapitalAPIServer) ListenBidAsks(ctx context.Context, req *Symbol) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenBidAsks not implemented")
}
func (*UnimplementedITICapitalAPIServer) ListenPortfolio(ctx context.Context, req *Portfolio) (*ListenPortfolioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenPortfolio not implemented")
}
func (*UnimplementedITICapitalAPIServer) ListenQuotes(ctx context.Context, req *Symbol) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenQuotes not implemented")
}
func (*UnimplementedITICapitalAPIServer) ListenTicks(ctx context.Context, req *Symbol) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListenTicks not implemented")
}
func (*UnimplementedITICapitalAPIServer) MoveOrder(ctx context.Context, req *MoveOrderRequest) (*ResponseWithFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveOrder not implemented")
}
func (*UnimplementedITICapitalAPIServer) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*ResponseWithFailed, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceOrder not implemented")
}

func RegisterITICapitalAPIServer(s *grpc.Server, srv ITICapitalAPIServer) {
	s.RegisterService(&_ITICapitalAPI_serviceDesc, srv)
}

func _ITICapitalAPI_CancelBidAsk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).CancelBidAsk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/CancelBidAsk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).CancelBidAsk(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).CancelOrder(ctx, req.(*OrderCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_CancelPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Portfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).CancelPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/CancelPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).CancelPortfolio(ctx, req.(*Portfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_CancelQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).CancelQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/CancelQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).CancelQuotes(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_CancelTicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).CancelTicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/CancelTicks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).CancelTicks(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_GetBars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).GetBars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/GetBars",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).GetBars(ctx, req.(*GetBarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_GetMyPortfolioData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyPortfolioDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).GetMyPortfolioData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/GetMyPortfolioData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).GetMyPortfolioData(ctx, req.(*GetMyPortfolioDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_GetPortfolioList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).GetPortfolioList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/GetPortfolioList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).GetPortfolioList(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_GetTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).GetTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/GetTrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).GetTrades(ctx, req.(*GetTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/GetSymbols",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).GetSymbols(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_IsConnected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).IsConnected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/IsConnected",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).IsConnected(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_ListenBidAsks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).ListenBidAsks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/ListenBidAsks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).ListenBidAsks(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_ListenPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Portfolio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).ListenPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/ListenPortfolio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).ListenPortfolio(ctx, req.(*Portfolio))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_ListenQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).ListenQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/ListenQuotes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).ListenQuotes(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_ListenTicks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Symbol)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).ListenTicks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/ListenTicks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).ListenTicks(ctx, req.(*Symbol))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_MoveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).MoveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/MoveOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).MoveOrder(ctx, req.(*MoveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ITICapitalAPI_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ITICapitalAPIServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iticapital.ITICapitalAPI/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ITICapitalAPIServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ITICapitalAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iticapital.ITICapitalAPI",
	HandlerType: (*ITICapitalAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelBidAsk",
			Handler:    _ITICapitalAPI_CancelBidAsk_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ITICapitalAPI_CancelOrder_Handler,
		},
		{
			MethodName: "CancelPortfolio",
			Handler:    _ITICapitalAPI_CancelPortfolio_Handler,
		},
		{
			MethodName: "CancelQuotes",
			Handler:    _ITICapitalAPI_CancelQuotes_Handler,
		},
		{
			MethodName: "CancelTicks",
			Handler:    _ITICapitalAPI_CancelTicks_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _ITICapitalAPI_Connect_Handler,
		},
		{
			MethodName: "GetBars",
			Handler:    _ITICapitalAPI_GetBars_Handler,
		},
		{
			MethodName: "GetMyPortfolioData",
			Handler:    _ITICapitalAPI_GetMyPortfolioData_Handler,
		},
		{
			MethodName: "GetPortfolioList",
			Handler:    _ITICapitalAPI_GetPortfolioList_Handler,
		},
		{
			MethodName: "GetTrades",
			Handler:    _ITICapitalAPI_GetTrades_Handler,
		},
		{
			MethodName: "GetSymbols",
			Handler:    _ITICapitalAPI_GetSymbols_Handler,
		},
		{
			MethodName: "IsConnected",
			Handler:    _ITICapitalAPI_IsConnected_Handler,
		},
		{
			MethodName: "ListenBidAsks",
			Handler:    _ITICapitalAPI_ListenBidAsks_Handler,
		},
		{
			MethodName: "ListenPortfolio",
			Handler:    _ITICapitalAPI_ListenPortfolio_Handler,
		},
		{
			MethodName: "ListenQuotes",
			Handler:    _ITICapitalAPI_ListenQuotes_Handler,
		},
		{
			MethodName: "ListenTicks",
			Handler:    _ITICapitalAPI_ListenTicks_Handler,
		},
		{
			MethodName: "MoveOrder",
			Handler:    _ITICapitalAPI_MoveOrder_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _ITICapitalAPI_PlaceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iticapital.proto",
}
